### PR TITLE
feat: upload documents from local JSON files

### PR DESCRIPTION
**Pull request by y-lakhdar**
## Proposed changes

After creating this [PR](https://github.com/coveo/cli/pull/604), we have decided to remove some of the business logic complexity from the [Coveo CLI](https://github.com/coveo/cli) and transfer it to the push-API-client.
With this PR, the push-api-client can now validate and upload documents from local files and directories.

Since this is a large PR, I recommend following the commit in order for an easier read. Most of the added files were copied from the https://github.com/coveo/cli.

### source.batchUpdateDocumentsFromFiles(sourceID, filesOrDirectories, callback, [{maxConcurrent])
Manage batches of items in a push source from a list of JSON files. See [Manage Batches of Items in a Push Source](https://docs.coveo.com/en/90)

**Kind**: instance method of [<code>Source</code>](#Source)

| Param | Type | Default | Description |
| --- | --- | --- | --- |
| sourceID | <code>string</code> |  | The unique identifier of the target Push source |
| filesOrDirectories | <code>Array.&lt;string&gt;</code> |  | A list of JSON files or directories (containing JSON files) from which to extract documents. |
| callback | <code>UploadBatchCallback</code> |  | Callback executed when a batch of documents is either successfully uploaded or when an error occurs during the upload |
| [{maxConcurrent] | <code>BatchUpdateDocumentsFromFiles</code> | <code>10}&#x3D;{}</code> |  |

<a name="Source+deleteDocument"></a>

## Acceptance Criteria

- [x] JSDoc annotates new property added in the exported interfaces and methods
- [x] The proposed changes are covered by unit tests

### CODE REVIEW

**Review by louis-bompart — CHANGES_REQUESTED** [review]
- [x] Fix the tests
- [x] List/describe the new public APIs in the PR description

**Review by louis-bompart — COMMENTED** [review]
As discussed let's put some samples :D 
I'll review again after they got in

**Comment by y-lakhdar** [comment]
> As discussed let's put some samples :D I'll review again after they got in

Good idea. [Here](https://github.com/coveo/push-api-client.js/pull/72/commits/cd7231e33b16f676a96d1b99ec63796b36f8fddd) is an example with the new API

**Comment by olamothe** [comment]
:gg: !!

**Pull request merged**
